[workspace]
members = ["crates/me-app", "crates/me-core"]
default-members = ["crates/me-app"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.98"
publish = false
license-file = "LICENSE"

[workspace.dependencies]
gpui = { version = "=0.2.2", default-features = false }
me-core = { path = "crates/me-core" }

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.release]
lto = "thin"
codegen-units = 1
