//! Shared property vocabulary so people, extraction and agents describe the same
//! relationships with the same keys. Installed without replacing existing definitions.
use crate::{EntityKind, PropertyDefinition, Result, domain::property_rules};
use EntityKind::*;

/// Key, label, value type, many values, subject kinds, linked kinds.
type Term = (
    &'static str,
    &'static str,
    &'static str,
    bool,
    &'static [EntityKind],
    &'static [EntityKind],
);
const CONTRACTS: &[EntityKind] = &[InsuranceContract, Contract, Subscription];
const PARTIES: &[EntityKind] = &[Person, Organization];
pub const PERSONAL_VOCABULARY: &[Term] = &[
    (
        "person.residence",
        "Residence",
        "entity",
        false,
        &[Person],
        &[Address],
    ),
    (
        "person.employer",
        "Employer",
        "entity",
        true,
        &[Person],
        &[Organization],
    ),
    (
        "person.occupation",
        "Occupation",
        "text",
        false,
        &[Person],
        &[],
    ),
    (
        "person.gross_income",
        "Gross income",
        "money",
        false,
        &[Person],
        &[],
    ),
    (
        "person.driving_licence_date",
        "Driving licence since",
        "date",
        false,
        &[Person],
        &[],
    ),
    (
        "person.owns",
        "Owns",
        "entity",
        true,
        &[Person],
        &[Vehicle, Property, BankAccount],
    ),
    (
        "address.postal_code",
        "Postal code",
        "identifier",
        false,
        &[Address],
        &[],
    ),
    ("address.city", "City", "text", false, &[Address], &[]),
    (
        "address.country",
        "Country",
        "identifier",
        false,
        &[Address],
        &[],
    ),
    ("vehicle.make", "Make", "text", false, &[Vehicle], &[]),
    ("vehicle.model", "Model", "text", false, &[Vehicle], &[]),
    (
        "vehicle.type_key",
        "Type key",
        "identifier",
        false,
        &[Vehicle],
        &[],
    ),
    (
        "vehicle.registration",
        "Registration",
        "identifier",
        false,
        &[Vehicle],
        &[],
    ),
    (
        "vehicle.first_registration",
        "First registration",
        "date",
        false,
        &[Vehicle],
        &[],
    ),
    (
        "vehicle.annual_mileage",
        "Annual mileage",
        "quantity",
        false,
        &[Vehicle],
        &[],
    ),
    (
        "contract.holder",
        "Holder",
        "entity",
        true,
        CONTRACTS,
        PARTIES,
    ),
    (
        "contract.provider",
        "Provider",
        "entity",
        false,
        CONTRACTS,
        &[Organization],
    ),
    (
        "contract.number",
        "Contract number",
        "identifier",
        false,
        CONTRACTS,
        &[],
    ),
    (
        "contract.premium",
        "Premium",
        "money",
        false,
        CONTRACTS,
        &[],
    ),
    (
        "contract.renewal_date",
        "Renewal date",
        "date",
        false,
        CONTRACTS,
        &[],
    ),
    (
        "contract.notice_period",
        "Notice period",
        "quantity",
        false,
        CONTRACTS,
        &[],
    ),
    (
        "insurance.insured_object",
        "Insures",
        "entity",
        true,
        &[InsuranceContract],
        &[],
    ),
    (
        "insurance.coverage",
        "Coverage",
        "text",
        true,
        &[InsuranceContract],
        &[],
    ),
    (
        "insurance.deductible",
        "Deductible",
        "money",
        false,
        &[InsuranceContract],
        &[],
    ),
    (
        "insurance.no_claims_class",
        "No-claims class",
        "identifier",
        false,
        &[InsuranceContract],
        &[],
    ),
    (
        "person.nationality",
        "Nationality",
        "identifier",
        false,
        &[Person],
        &[],
    ),
    (
        "person.net_income",
        "Net income",
        "money",
        false,
        &[Person],
        &[],
    ),
    (
        "person.wage_tax",
        "Wage tax",
        "money",
        false,
        &[Person],
        &[],
    ),
    (
        "person.solidarity_surcharge",
        "Solidarity surcharge",
        "money",
        false,
        &[Person],
        &[],
    ),
    (
        "person.church_tax",
        "Church tax",
        "money",
        false,
        &[Person],
        &[],
    ),
    (
        "person.pension_contribution",
        "Pension contribution",
        "money",
        false,
        &[Person],
        &[],
    ),
    (
        "person.health_insurance_contribution",
        "Health insurance contribution",
        "money",
        false,
        &[Person],
        &[],
    ),
    (
        "person.care_insurance_contribution",
        "Care insurance contribution",
        "money",
        false,
        &[Person],
        &[],
    ),
    (
        "person.unemployment_insurance_contribution",
        "Unemployment insurance contribution",
        "money",
        false,
        &[Person],
        &[],
    ),
    (
        "person.taxable_income",
        "Taxable income",
        "money",
        false,
        &[Person],
        &[],
    ),
    (
        "person.income_tax_assessed",
        "Assessed income tax",
        "money",
        false,
        &[Person],
        &[],
    ),
    (
        "person.tax_balance",
        "Tax refund or back payment",
        "money",
        false,
        &[Person],
        &[],
    ),
    (
        "person.tax_payment_due",
        "Tax payment due",
        "date",
        false,
        &[Person],
        &[],
    ),
    (
        "person.tax_class",
        "Tax class",
        "text",
        false,
        &[Person],
        &[],
    ),
    (
        "person.employee_number",
        "Employee number",
        "identifier",
        false,
        &[Person],
        &[],
    ),
    (
        "person.tax_number",
        "Tax number",
        "identifier",
        false,
        &[Person],
        &[],
    ),
    (
        "person.tax_office",
        "Tax office",
        "entity",
        false,
        &[Person],
        &[Organization],
    ),
    (
        "person.health_insurer",
        "Health insurer",
        "entity",
        false,
        &[Person],
        &[Organization],
    ),
    (
        "person.health_insurance_number",
        "Health insurance number",
        "identifier",
        false,
        &[Person],
        &[],
    ),
    (
        "person.government_id",
        "Identity document",
        "entity",
        true,
        &[Person],
        &[GovernmentId],
    ),
    (
        "person.bank_account",
        "Bank account",
        "entity",
        true,
        &[Person],
        &[BankAccount],
    ),
    (
        "government_id.kind",
        "Document kind",
        "text",
        false,
        &[GovernmentId],
        &[],
    ),
    (
        "government_id.number",
        "Document number",
        "identifier",
        false,
        &[GovernmentId],
        &[],
    ),
    (
        "government_id.issued",
        "Issued on",
        "date",
        false,
        &[GovernmentId],
        &[],
    ),
    (
        "government_id.expires",
        "Valid until",
        "date",
        false,
        &[GovernmentId],
        &[],
    ),
    (
        "government_id.issuer",
        "Issued by",
        "text",
        false,
        &[GovernmentId],
        &[],
    ),
    (
        "bank_account.iban",
        "IBAN",
        "identifier",
        false,
        &[BankAccount],
        &[],
    ),
    (
        "bank_account.bic",
        "BIC",
        "identifier",
        false,
        &[BankAccount],
        &[],
    ),
    (
        "bank_account.bank",
        "Bank",
        "entity",
        false,
        &[BankAccount],
        &[Organization],
    ),
    (
        "vehicle.vin",
        "Vehicle identification number",
        "identifier",
        false,
        &[Vehicle],
        &[],
    ),
    ("address.street", "Street", "text", false, &[Address], &[]),
    (
        "insurance.kind",
        "Insurance kind",
        "text",
        false,
        &[InsuranceContract],
        &[],
    ),
    (
        "contract.start_date",
        "Start date",
        "date",
        false,
        CONTRACTS,
        &[],
    ),
    (
        "contract.end_date",
        "End date",
        "date",
        false,
        CONTRACTS,
        &[],
    ),
    (
        "contract.payment",
        "Recurring payment",
        "money",
        false,
        CONTRACTS,
        &[],
    ),
];

pub fn vocabulary() -> impl Iterator<Item = PropertyDefinition> {
    PERSONAL_VOCABULARY
        .iter()
        .map(
            |(key, label, value_type, many, subjects, objects)| PropertyDefinition {
                key: (*key).into(),
                label: (*label).into(),
                value_type: (*value_type).into(),
                many: *many,
                subject_kinds: subjects.to_vec(),
                object_kinds: objects.to_vec(),
            },
        )
}

/// Adds missing terms. A user's existing definition of the same key is kept.
pub(crate) fn install(db: &rusqlite::Connection) -> Result<()> {
    for p in vocabulary() {
        db.execute(
            "INSERT OR IGNORE INTO property_definition VALUES(?,?,?,?,'confirm',?,1)",
            rusqlite::params![
                p.key,
                p.label,
                p.value_type,
                if p.many { "many" } else { "one" },
                property_rules(&p).to_string()
            ],
        )?;
    }
    Ok(())
}
